### ISSUE TITLE
MVP Project Plan / Features Needed

### ISSUE THREAD

**Issue by ytsruh** [ytsruh/wrongmove#15]
Public Features
- [x]  See all sales listings
- [x]  See all rental listings
- [x]  See a single sale listing
- [x]  See a single rental listing
- [x]  See a list of all agents

Agent logged in features
- [x]  Log in page & functionality for agent
- [x]  Agent can see dashboard
- [x]  Agent can CRUD listing for sale
- [x]  Agent can add & remove images to a sales listing
- [x]  Agent can CRUD listing for rental
- [x]  Agent can add & remove images to a rental listing
- [x]  Agents should be able to see their listings in charts/graphs (aka statistics)
- [x]  Agent can edit their profile

* CRUD = Create, Read, Update & Delete

**Comment by ytsruh** [comment]
@RyanBriggsDev i've updated the MVP above. Let me know what you think, if anything should be added or removed?

**Comment by ytsruh** [comment]
We agreed to drop the User functionality from the project
